name: windows-llvm-msvc-build

permissions:
  contents: write
  
on:  
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    env:
      BUILD_TYPE: Release
    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@main
      with:
          path: llvm-msvc
          submodules: 'recursive'
          
    - name: Build llvm
      run: |
       cmake -Bbuild -G "Visual Studio 17 2022" -A x64 --parallel 4 -- /p:CL_MPcount=4 `
        -DLLVM_ENABLE_RPMALLOC=ON `
        -DHAVE_STD_IS_TRIVIALLY_COPYABLE=0 -DLLVM_TOOL_LLVM_SHLIB_BUILD=OFF `
        -DLLVM_INCLUDE_TESTS=OFF `
        -DLLVM_INCLUDE_TOOLS=ON `
        -DLLVM_INCLUDE_EXAMPLES=OFF `
        -DLLDB_ENABLE_PYTHON=OFF `
        -DLLVM_ENABLE_LIBXML2=OFF `
        -DLLVM_ENABLE_ZLIB=OFF `
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
        -DLLVM_USE_CRT_RELEASE=MT `
        -DLLVM_OBFUSCATION_LINK_INTO_TOOLS=ON `
        -DCMAKE_INSTALL_PREFIX=install `
        -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64;Mips;RISCV" `
        -DLLVM_ENABLE_PROJECTS="clang;lld;lldb;clang-tools-extra" `
        llvm-msvc\\llvm
        cmake --build build --config ${{ env.BUILD_TYPE }} --target install --verbose --parallel 4 -- /p:CL_MPcount=4
        
    - name: Package llvm
      run: |
        7z a -t7z -ms=10m -mmt=on -mf=on -mhc=on -m0=LZMA2 -mx=9 windows-llvm-msvc.7z install
        
    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: windows-llvm-msvc
        path: windows-llvm-msvc.7z
        
    - name: Release
      uses: softprops/action-gh-release@master
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: windows-llvm-msvc.7z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
